import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import initSqlJs, { type SqlJsStatic } from "sql.js";
import { Deck, Model, Note, Package } from "ankipack";
import type { GeneratedCard } from "@sluggo/shared";
import { validateClozeDeletions } from "@sluggo/shared";

/**
 * Static imports of sql.js and ankipack are intentional. With @sluggo/apkg
 * marked as a server external package (and removed from transpilePackages),
 * Next.js's bundler emits a literal `require("sql.js")` at this site instead
 * of inlining sql.js's Emscripten UMD wrapper (which crashes with
 * "Cannot set properties of undefined"). The literal require is also what
 * Vercel's file tracer needs to actually ship the package with the function.
 *
 * The wasm binary is loaded explicitly via createRequire+readFile because
 * sql.js's default wasm path resolution doesn't work under Next/Turbopack.
 */

const localRequire = createRequire(import.meta.url);

let sqlPromise: Promise<SqlJsStatic> | null = null;

async function loadWasmBinary(): Promise<ArrayBuffer | undefined> {
  try {
    const wasmPath = localRequire.resolve("sql.js/dist/sql-wasm.wasm");
    const buf = await readFile(wasmPath);
    return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  } catch {
    return undefined;
  }
}

async function getSql(): Promise<SqlJsStatic> {
  if (!sqlPromise) {
    sqlPromise = (async () => {
      const wasmBinary = await loadWasmBinary();
      return initSqlJs(
        wasmBinary ? ({ wasmBinary } as unknown as Partial<EmscriptenModule>) : {},
      );
    })();
  }
  return sqlPromise;
}

type EmscriptenModule = Record<string, unknown>;

export interface ExportDeckOptions {
  deckName: string;
  cards: GeneratedCard[];
  description?: string;
}

export interface ExportResult {
  bytes: Uint8Array;
  cardCount: number;
  skipped: number;
}

export async function buildApkg(options: ExportDeckOptions): Promise<ExportResult> {
  const SQL = await getSql();
  const basicModel = Model.basic();
  const clozeModel = Model.cloze();

  const deck = new Deck({
    name: options.deckName,
    description: options.description ?? "Generated by Sluggo",
  });

  let cardCount = 0;
  let skipped = 0;

  for (const card of options.cards) {
    if (card.type === "basic") {
      const front = card.front?.trim();
      const back = card.back?.trim();
      if (!front || !back) {
        skipped += 1;
        continue;
      }
      deck.addNote(
        new Note({ model: basicModel, fields: [front, back], tags: card.tags ?? [] }),
      );
      cardCount += 1;
      continue;
    }

    const clozeText = card.clozeText?.trim();
    if (!clozeText || !validateClozeDeletions(clozeText)) {
      skipped += 1;
      continue;
    }

    const fields = [clozeText, card.extra?.trim() ?? ""];
    deck.addNote(
      new Note({ model: clozeModel, fields, tags: card.tags ?? [] }),
    );
    cardCount += 1;
  }

  const pkg = new Package();
  pkg.addDeck(deck);
  const bytes = await pkg.toUint8Array(SQL);

  return { bytes, cardCount, skipped };
}

export async function writeApkgToFile(
  outputPath: string,
  options: ExportDeckOptions,
): Promise<ExportResult> {
  const SQL = await getSql();
  const result = await buildApkg(options);

  const pkg = new Package();
  const deck = new Deck({ name: options.deckName });
  const basicModel = Model.basic();
  const clozeModel = Model.cloze();

  for (const card of options.cards) {
    if (card.type === "basic") {
      const front = card.front?.trim();
      const back = card.back?.trim();
      if (!front || !back) continue;
      deck.addNote(new Note({ model: basicModel, fields: [front, back], tags: card.tags ?? [] }));
    } else {
      const clozeText = card.clozeText?.trim();
      if (!clozeText || !validateClozeDeletions(clozeText)) continue;
      deck.addNote(
        new Note({
          model: clozeModel,
          fields: [clozeText, card.extra?.trim() ?? ""],
          tags: card.tags ?? [],
        }),
      );
    }
  }

  pkg.addDeck(deck);
  await pkg.writeToFile(outputPath, SQL);
  return result;
}

export function draftCardsToGenerated(
  cards: Array<{
    type: "basic" | "cloze";
    front: string | null;
    back: string | null;
    cloze_text: string | null;
    extra: string | null;
    tags: string[];
  }>,
): GeneratedCard[] {
  return cards.map((card) =>
    card.type === "basic"
      ? {
          type: "basic" as const,
          front: card.front ?? undefined,
          back: card.back ?? undefined,
          extra: card.extra ?? undefined,
          tags: card.tags,
        }
      : {
          type: "cloze" as const,
          clozeText: card.cloze_text ?? undefined,
          extra: card.extra ?? undefined,
          tags: card.tags,
        },
  );
}
