import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { SqlJsStatic } from "sql.js";
import type { GeneratedCard } from "@sluggo/shared";
import { validateClozeDeletions } from "@sluggo/shared";

/**
 * sql.js and ankipack are loaded with `webpackIgnore` dynamic imports so the
 * Next.js bundler leaves the calls untouched. Inlining sql.js's Emscripten
 * UMD wrapper crashes with "Cannot set properties of undefined", and going
 * through webpack's CJS→ESM interop on `await import("module")` was hiding
 * `createRequire` behind `.default` on Vercel ("b is not a function").
 *
 * `process.cwd()` is used as a stable base for `createRequire`; the
 * alternative (`import.meta.url`) gets baked at build time and leaks the
 * dev machine path into the production bundle.
 */

type Initializer = (config?: Record<string, unknown>) => Promise<SqlJsStatic>;

interface AnkipackModule {
  Deck: new (opts: { name: string; description?: string }) => AnkipackDeck;
  Model: { basic(): unknown; cloze(): unknown };
  Note: new (opts: { model: unknown; fields: string[]; tags?: string[] }) => unknown;
  Package: new () => AnkipackPackage;
}

interface AnkipackDeck {
  addNote(note: unknown): void;
}

interface AnkipackPackage {
  addDeck(deck: AnkipackDeck): void;
  toUint8Array(sql: SqlJsStatic): Promise<Uint8Array>;
  writeToFile(path: string, sql: SqlJsStatic): Promise<void>;
}

const baseRequire = createRequire(
  pathToFileURL(resolve(process.cwd(), "package.json")).href,
);

let sqlPromise: Promise<SqlJsStatic> | null = null;
let ankipackPromise: Promise<AnkipackModule> | null = null;

async function loadWasmBinary(): Promise<ArrayBuffer | undefined> {
  try {
    const wasmPath = baseRequire.resolve("sql.js/dist/sql-wasm.wasm");
    const buf = await readFile(wasmPath);
    return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  } catch {
    return undefined;
  }
}

async function getSql(): Promise<SqlJsStatic> {
  if (!sqlPromise) {
    sqlPromise = (async () => {
      const mod = (await import(/* webpackIgnore: true */ "sql.js")) as unknown as {
        default?: Initializer;
      };
      const initSqlJs: Initializer = mod.default ?? (mod as unknown as Initializer);
      const wasmBinary = await loadWasmBinary();
      return initSqlJs(wasmBinary ? { wasmBinary } : {});
    })();
  }
  return sqlPromise;
}

async function getAnkipack(): Promise<AnkipackModule> {
  if (!ankipackPromise) {
    ankipackPromise = (async () => {
      const mod = (await import(/* webpackIgnore: true */ "ankipack")) as unknown as {
        default?: AnkipackModule;
      } & AnkipackModule;
      return mod.default ?? (mod as AnkipackModule);
    })();
  }
  return ankipackPromise;
}

export interface ExportDeckOptions {
  deckName: string;
  cards: GeneratedCard[];
  description?: string;
}

export interface ExportResult {
  bytes: Uint8Array;
  cardCount: number;
  skipped: number;
}

export async function buildApkg(options: ExportDeckOptions): Promise<ExportResult> {
  const SQL = await getSql();
  const { Deck, Model, Note, Package } = await getAnkipack();

  const basicModel = Model.basic();
  const clozeModel = Model.cloze();

  const deck = new Deck({
    name: options.deckName,
    description: options.description ?? "Generated by Sluggo",
  });

  let cardCount = 0;
  let skipped = 0;

  for (const card of options.cards) {
    if (card.type === "basic") {
      const front = card.front?.trim();
      const back = card.back?.trim();
      if (!front || !back) {
        skipped += 1;
        continue;
      }
      deck.addNote(
        new Note({ model: basicModel, fields: [front, back], tags: card.tags ?? [] }),
      );
      cardCount += 1;
      continue;
    }

    const clozeText = card.clozeText?.trim();
    if (!clozeText || !validateClozeDeletions(clozeText)) {
      skipped += 1;
      continue;
    }

    const fields = [clozeText, card.extra?.trim() ?? ""];
    deck.addNote(
      new Note({ model: clozeModel, fields, tags: card.tags ?? [] }),
    );
    cardCount += 1;
  }

  const pkg = new Package();
  pkg.addDeck(deck);
  const bytes = await pkg.toUint8Array(SQL);

  return { bytes, cardCount, skipped };
}

export async function writeApkgToFile(
  outputPath: string,
  options: ExportDeckOptions,
): Promise<ExportResult> {
  const SQL = await getSql();
  const { Deck, Model, Note, Package } = await getAnkipack();
  const result = await buildApkg(options);

  const pkg = new Package();
  const deck = new Deck({ name: options.deckName });
  const basicModel = Model.basic();
  const clozeModel = Model.cloze();

  for (const card of options.cards) {
    if (card.type === "basic") {
      const front = card.front?.trim();
      const back = card.back?.trim();
      if (!front || !back) continue;
      deck.addNote(new Note({ model: basicModel, fields: [front, back], tags: card.tags ?? [] }));
    } else {
      const clozeText = card.clozeText?.trim();
      if (!clozeText || !validateClozeDeletions(clozeText)) continue;
      deck.addNote(
        new Note({
          model: clozeModel,
          fields: [clozeText, card.extra?.trim() ?? ""],
          tags: card.tags ?? [],
        }),
      );
    }
  }

  pkg.addDeck(deck);
  await pkg.writeToFile(outputPath, SQL);
  return result;
}

export function draftCardsToGenerated(
  cards: Array<{
    type: "basic" | "cloze";
    front: string | null;
    back: string | null;
    cloze_text: string | null;
    extra: string | null;
    tags: string[];
  }>,
): GeneratedCard[] {
  return cards.map((card) =>
    card.type === "basic"
      ? {
          type: "basic" as const,
          front: card.front ?? undefined,
          back: card.back ?? undefined,
          extra: card.extra ?? undefined,
          tags: card.tags,
        }
      : {
          type: "cloze" as const,
          clozeText: card.cloze_text ?? undefined,
          extra: card.extra ?? undefined,
          tags: card.tags,
        },
  );
}
