import { writeFile } from "node:fs/promises";
import { Deck, Model, Note, Package } from "ankipack";
import type { GeneratedCard } from "@deephaus/shared";
import { validateClozeDeletions } from "@deephaus/shared";
import { prepareCardsForApkgExport, type MediaFetcher } from "./media.js";
import { getSql } from "./sql.js";

export type { MediaFetcher };

export interface ExportDeckOptions {
  deckName: string;
  cards: GeneratedCard[];
  description?: string;
  fetchMedia?: MediaFetcher;
}

export interface ExportResult {
  bytes: Uint8Array;
  cardCount: number;
  skipped: number;
  mediaBundled: number;
  mediaSkipped: number;
}

function addCardToDeck(deck: Deck, basicModel: Model, clozeModel: Model, card: GeneratedCard) {
  if (card.type === "basic") {
    const front = card.front?.trim();
    const back = card.back?.trim();
    if (!front || !back) return false;

    deck.addNote(
      new Note({ model: basicModel, fields: [front, back], tags: card.tags ?? [] }),
    );
    return true;
  }

  const clozeText = card.clozeText?.trim();
  if (!clozeText || !validateClozeDeletions(clozeText)) return false;

  deck.addNote(
    new Note({
      model: clozeModel,
      fields: [clozeText, card.extra?.trim() ?? ""],
      tags: card.tags ?? [],
    }),
  );
  return true;
}

async function assemblePackage(options: ExportDeckOptions) {
  const { cards, media, mediaBundled, mediaSkipped } = await prepareCardsForApkgExport(
    options.cards,
    options.fetchMedia,
  );

  const basicModel = Model.basic();
  const clozeModel = Model.cloze();
  const deck = new Deck({
    name: options.deckName,
    description: options.description ?? "Generated by DeepHaus",
  });

  let cardCount = 0;
  let skipped = 0;

  for (const card of cards) {
    if (addCardToDeck(deck, basicModel, clozeModel, card)) {
      cardCount += 1;
    } else {
      skipped += 1;
    }
  }

  const pkg = new Package();
  pkg.addDeck(deck);
  for (const file of media) {
    pkg.addMedia(file.filename, file.data);
  }

  return { pkg, cardCount, skipped, mediaBundled, mediaSkipped };
}

export async function buildApkg(options: ExportDeckOptions): Promise<ExportResult> {
  const SQL = await getSql();
  const { pkg, cardCount, skipped, mediaBundled, mediaSkipped } = await assemblePackage(options);
  const bytes = await pkg.toUint8Array(SQL);

  return { bytes, cardCount, skipped, mediaBundled, mediaSkipped };
}

export async function writeApkgToFile(
  outputPath: string,
  options: ExportDeckOptions,
): Promise<ExportResult> {
  const result = await buildApkg(options);
  await writeFile(outputPath, result.bytes);
  return result;
}

export function draftCardsToGenerated(
  cards: Array<{
    type: "basic" | "cloze";
    front: string | null;
    back: string | null;
    cloze_text: string | null;
    extra: string | null;
    tags: string[];
  }>,
): GeneratedCard[] {
  return cards.map((card) =>
    card.type === "basic"
      ? {
          type: "basic" as const,
          front: card.front ?? undefined,
          back: card.back ?? undefined,
          extra: card.extra ?? undefined,
          tags: card.tags,
        }
      : {
          type: "cloze" as const,
          clozeText: card.cloze_text ?? undefined,
          extra: card.extra ?? undefined,
          tags: card.tags,
        },
  );
}
